### ISSUE TITLE
Is it possible to declare poincut variables?

### ISSUE THREAD

**Issue by sshikov** [igor-suhorukov/aspectj-scripting#3]
For example, look into [call logger](http://erik.doernenburg.com/2008/09/call-graph-visualisation-with-aspectj-and-dot/) implementation. We need to have a call stack available from pointcuts.

**Comment by igor-suhorukov** [comment]
You can use <b>joinPoint</b> implicit variable inside /configuration/aspects/process/expression
For <a href="http://habrahabr.ru/post/267009/">example</a> :
                log.put("level", joinPoint.getSignature().getName());
                log.put("srcf", joinPoint.getSourceLocation().getFileName());
                log.put("srcl", joinPoint.getSourceLocation().getLine());

and also Thread.currentThread().getStackTrace() can help you

**Comment by sshikov** [comment]
Looks like you didn't get the point. I've not asked about pointcut info. I just need [global] variables to pass information between pointcuts. Its not obvious how to declare such (if possible). Probably some examples/documentation will be great addition.

**Comment by igor-suhorukov** [comment]
/globalContext/init/expression/ 
globalThreadLocalVariable=new  ThreadLocal();
globalCounter = new AtomicInteger();
globalList = new CopyOnWriteArrayList();
